// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.commands;
import edu.wpi.first.wpilibj.command.Command;
import frc.robot.Robot;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 *
 */
public class Autonomous extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    static double degToRad = Math.PI/180.0;

    // static enum AutonState{
    //     BEGIN, DISMOUNT, ADVANCE, TURN, APPROACH, END
    // }
    int curStage = 0;
    final double distancePerPulse = 6*Math.PI/360;

    private double distR=0, distL=0;

    private final double dismountDistance = 24; //need to measure so that we aren't going off platform
    private final double dismountSpeed = 0.3;
    private final double advanceDistance = 56;
    private final double advanceSpeed = 0.1;
    private double turnDegrees = 30;
    private double turnSpeed = 0.1;
    private final double approachDistance = 24;
    private final double approachSpeed = 0.1;
    private double invert = -1;

    private int m_Position;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public Autonomous(int Position) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        m_Position = Position;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    
    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        Robot.driveSub.leftPairEncoder.setDistancePerPulse(distancePerPulse);
        Robot.driveSub.rightPairEncoder.setDistancePerPulse(distancePerPulse); //6 inch wheel, one pulse per inch
        Robot.driveSub.resetEncoders();
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        distR = Robot.driveSub.rightPairEncoder.getDistance();
        distL = Robot.driveSub.leftPairEncoder.getDistance();

        SmartDashboard.putString("Dist L", Double.toString(distL));
        SmartDashboard.putString("Dist R", Double.toString(distR));
        switch(this.curStage){
            case 0://begin
                new limelight();
                nextStage();
                break;
            
            case 1:
                if(AS_Advance(0.5,5.5)){
                    nextStage();
                }
                break;
            case 2:
                if(AS_TurnRight(0.90, 0.35, 410)){
                    nextStage();
                }
                break;
            case 3:
                if(AS_Advance(0.5, 1.3)){
                    nextStage();
                }
                break;
            case 4:
                if(AS_TurnLeft(0.35, 0.90, 280)){
                    nextStage();
                }
                break;
            case 5:
                if(AS_Advance(0.5, 4.0)){
                    nextStage();
                }
                break;
            case 6:
                if(AS_TurnLeft(0.3, 0.85, 270)){
                    nextStage();
                }
                break;
            case 7:
                if(AS_Advance(0.5, 8.5)){
                    // nextStage();
                    this.curStage=-1;
                }
                break;
            case 8:
                if(AS_TurnRight(-1,-0.45, 410)){
                    nextStage();
                }
                break;
            default:
                Robot.driveSub.resetEncoders();
                Robot.driveSub.stop();
        }
    }

    private void nextStage(){
        Robot.driveSub.resetEncoders();
        this.curStage++;
    }
    private boolean AS_Advance(double advanceSpeed, double advanceDistance){//26.67 inches = 1 unit of distance 
        double avg = 0.5*(distR+distL);
        SmartDashboard.putString("avg", Double.toString(avg));
        Robot.driveSub.driveStraight(advanceSpeed * invert);
        return (avg >= advanceDistance);
    }

    private boolean AS_TurnLeft(double leftDistance, double rightDistance, double turnDegrees){
        double dist = -0.5*(distR-distL);
        // double degreesTurned=degToRad*dist/16.0; // (arclength / robot radius)
        double degreesTurned = Math.abs(distR);
        SmartDashboard.putString("degreesTurned", Double.toString(degreesTurned));
        SmartDashboard.putString("dist", Double.toString(dist));
        Robot.driveSub.swivelLeft(leftDistance, rightDistance);
        return (degreesTurned >= turnDegrees);
    }

    private boolean AS_TurnRight(double leftDistance, double rightDistance, double turnDegrees){
        double dist = -0.5*(distR-distL);
        // double degreesTurned=degToRad*dist/16.0; // (arclength / robot radius)
        double degreesTurned = Math.abs(distL);
        SmartDashboard.putString("degreesTurned", Double.toString(degreesTurned));
        SmartDashboard.putString("dist", Double.toString(dist));
        Robot.driveSub.swivelRight(leftDistance, rightDistance);
        return (degreesTurned >= turnDegrees);
    }


    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
